### PR TITLE
Enhanced Feature Extraction and Output Customization in Capa CLI

### PR DESCRIPTION
**Pull request by jorgeaduran**
# Enhanced Feature Extraction and Output Customization in Capa CLI

This PR introduces a series of optimizations and enhancements to the Capa CLI tool, focusing on improving the feature extraction process, particularly with .NET files, and adding new CLI options for better output management and feature data inclusion.

### .NET-Aware Feature Extraction
The feature extraction logic has been optimized to include conditional checks for .NET files, ensuring that file features are accurately extracted based on the file type. This enhances the tool's ability to work with a broader range of executable formats and improves the overall accuracy of the analysis.

### CLI Options for Output Customization

- **JSON Output Path (`-o` or `--output`)**: Users can now specify a custom path for the JSON output using the `-o` or `--output` option followed by the desired file path. This allows for greater flexibility in how and where analysis results are saved. For example, specifying `-o="path_to_json"` will direct the tool to save the JSON output to the specified path.
- **Feature Map Inclusion (`-m` or `--map-features`)**: With the new `--map-features` flag, users can opt to include a comprehensive map of features found during the analysis in the JSON output. This feature is particularly useful for detailed analyses where understanding the specific features matched is crucial. To include the feature map in the JSON output, simply add `--m` to the command line.

## Implementation Details

- The feature collection process now leverages Rust's efficient data handling capabilities to streamline the aggregation and indexing of rule matches, significantly reducing the complexity and improving the performance of the analysis.
- Conditional logic has been added to ensure that file features are only included for .NET files, addressing the unique analysis requirements of these files.
- The introduction of CLI options for output customization provides users with enhanced control over the analysis process, enabling more tailored and detailed examination of binary files.

## Usage

To utilize the new output customization features, you can specify the JSON output path and decide whether to include the feature map in the output as follows:

`capa_cli -o="path_to_json" --m [other options] <file_to_analyze>`

### CODE REVIEW

**Comment by marirs** [comment]
Hey - Thanks once again for this PR. This is also pretty good!
Btw: I invite you to see this repo as well: https://github.com/marirs/strings-rs (This is similar to mandiant FLOSS) :)

**Comment by jorgeaduran** [comment]
Thank you for accepting the PR and for your kind words. I truly appreciate the recognition and am glad to have been able to contribute.

Also, thank you for the invitation to check out the [strings-rs](https://github.com/marirs/strings-rs) repository. It sounds interesting, especially with its similarity to Mandiant's FLOSS. I'll definitely take a look at it.

Looking forward to potentially contributing more in the future!

**Comment by marirs** [comment]
As my sincere gratitude, I added you as an author in the Cargo.toml file :)

**Comment by marirs** [comment]
if it interests you, take a look at this as well: https://github.com/marirs/traffiq
Its like an extended netcat :)

**Pull request merged**
