### PR TITLE
Major Enhancements in Feature Detection and JSON Output Management

### PR DESCRIPTION
**Pull request by jorgeaduran**
### Description

This PR introduces a series of comprehensive updates aimed at improving the efficiency, accuracy, and user control over feature detection and JSON output generation within our project. The changes span across various components, refining both the underlying logic for string extraction and the mechanisms for data representation. Below is a summary of the key enhancements:

#### Feature Detection Improvements
- **Optimized Unicode String Extraction:** We've refined the `extract_unicode_strings` function to better handle UTF-16LE and UTF-16BE encodings, employing targeted regex patterns that enhance the accuracy of our string detection efforts.
- **Advanced Bytes Feature Evaluation:** The evaluation method in `BytesFeature` now utilizes a sliding window approach, allowing us to detect specified byte sequences more flexibly across different contexts.

#### JSON Output Management
- **Enhanced JSON Generation for Map Features:** With the new `-f` parameter, users can now filter map features by type, making the JSON output more relevant and manageable. This feature is triggered by the `-m` flag and requires specifying an output path using the `-o` parameter.
- **Clean String Function:** We've added a function to sanitize extracted strings, ensuring the output is free from null characters and non-printable ASCII characters.

#### Safety and Usability Enhancements
- **Boundary Checks and Error Handling:** Significant updates have been made to prevent buffer over-reads and integer overflows, particularly in the `detect_ascii_len` function, enhancing the overall safety of our operations.
- **CLI Options Expansion:** The introduction of `filter_map_features` in `CliOpts` allows for even finer control over the features to be processed.

### Why This Matters
These updates collectively represent a significant leap forward in our project's capability to accurately detect and represent data features, catering to a broader range of encoding scenarios and user needs. By improving efficiency, accuracy, and control, we are setting a solid foundation for future developments and applications of our project.

### Testing
- Test cases cover a variety of scenarios, including different encoding formats, feature types, and JSON output configurations.

I look forward to your feedback and any further suggestions for improvement!

### CODE REVIEW

**Comment by jorgeaduran** [comment]
PD: For it to compile it is necessary to accept the smda PR

**Comment by marirs** [comment]
Hey thanks again..

1 Quick Question

This which I refactored:
```rust
if let Some(Yaml::String(s)) = rule.meta.get(&Yaml::String("namespace".to_string())) {
                self.capability_namespaces.insert(rule.name.clone(), s.clone());
                let first_non_zero_address = caps
                    .iter()
                    .find(|&&(addr, _)| addr != 0)
                    .map(|&(addr, _)| addr)
                    .unwrap_or(0);

                let _ = self
                    .capabilities_associations
                    .entry(rule.name.clone())
                    .or_insert_with(|| CapabilityAssociation {
                        attack: local_attacks_set.clone(),
                        mbc: local_mbc_set.clone(),
                        namespace: s.clone(),
                        name: rule.name.clone(),
                        address: first_non_zero_address as usize,
                    });
            }
```

and this (which you reverted):
```rust
if let Some(namespace) = rule.meta.get(&Yaml::String("namespace".to_string())) {
                if let Yaml::String(s) = namespace {
                    self.capability_namespaces
                        .insert(rule.name.clone(), s.clone());
                    let first_non_zero_address = caps
                        .iter()
                        .find(|&&(addr, _)| addr != 0)
                        .map(|&(addr, _)| addr)
                        .unwrap_or(0);

                    let _ = self
                        .capabilities_associations
                        .entry(rule.name.clone())
                        .or_insert_with(|| CapabilityAssociation {
                            attack: local_attacks_set.clone(),
                            mbc: local_mbc_set.clone(),
                            namespace: s.clone(),
                            name: rule.name.clone(),
                            address: first_non_zero_address as usize,
                        });
                }
            }
```

are the same. Any reason why you reverted back?

**Comment by jorgeaduran** [comment]
Thank you for highlighting this. After a closer look, it seems the modifications indeed revolve around formatting rather than functional changes. It's possible that I worked on a version of the code that didn't include your recent changes, leading to the unintended omission of your refinements. I apologize for any confusion this may have caused and will make sure to synchronize changes more carefully in the future to avoid such oversights.

**Comment by marirs** [comment]
Nah - dont worry about that.. I'll make the update now!
Just thought maybe it broke something.
Thanks again so much for your awesome pushes :)

**Comment by marirs** [comment]
Done I've pushed this as well :)

Thanks

**Comment by jorgeaduran** [comment]
Thank you for your understanding and for handling the update. I'm glad it didn't cause any issues. I appreciate the collaboration and look forward to our continued work together. Thanks again! :)

**Pull request merged**
